### ISSUE TITLE
Calendar backgroundColor ?

### ISSUE THREAD

**Issue by ottopic** [hansemannn/titanium-calendar#3]
Hello @hansemannn, is there a way to change calendar 📆 background color? I'm looking for compatibility with dark mode versione, but I don't find the way.

Thanks 🙏

**Comment by hansemannn** [comment]
Dark mode is supported since last week with the latest master version. You can build it from source

**Comment by ottopic** [comment]
Thank you for your answer but I don't understand something.
Background Color is not exposed, isn't it? If I understand how to use darkmode module I have to costumize every colors of my UI using global var generated in initializeColors() function, isn't it?

😕
